site_name: Paquete de Apertura de Datos de la República Argentina
site_url: https://datosgobar.github.io/paquete-apertura-datos
site_description: Recursos para la apertura de datos públicos nacionales y sub-nacionales en Argentina.
site_author: Datos Argentina
repo_url: https://github.com/datosgobar/paquete-apertura-datos/

nav:
  - Inicio: index.md
  - Material introductorio: https://www.argentina.gob.ar/sites/default/files/2._kit_de_datos_abiertos.pdf
  - Guías de buenas prácticas:
    - Guía para la publicación de datos en formatos abiertos: guia-abiertos.md
    - Guía para la identificación y uso de entidades interoperables: guia-interoperables.md
    - Guía para el uso y la publicación de metadatos: guia-metadatos.md
    # - "Datasets sugeridos: especificaciones": datasets-especificaciones.md
  - Guías de implementación:
    - Guía para la apertura de datos en organismos de la Administración Pública Nacional: guia-apn.md
    - Guía para la apertura de datos en gobiernos provinciales y locales: guia-subnacionales.md
  - Marco legal:
    - Decreto 117/2016 "Plan de Apertura de Datos": decreto-117-2016.md
    # - Resolución xx/2019 "Política de Apertura de Datos": resolucion-xx-2019.md
    - Perfil de Aplicación Nacional de Metadatos para Datos Abiertos: perfil-metadatos.md
  - Herramientas: herramientas.md
  - Glosario: glosario.md

docs_dir: docs/src
theme: datosgobar_docs

# # extensiones recomendadas con este theme
markdown_extensions:
  - markdown.extensions.toc:
      anchorlink: true
      permalink: '&#128279;'
  - fenced_code
  - codehilite
  - admonition

extra_css:
  # - css/extra_rtd.css
  - css/table_styles.css

google_analytics: ['UA-91435482-1', "https://datosgobar.github.io/paquete-apertura-datos/"]
